language: php
sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

addons:
  # postgresql: "9.6"

services:
  # - postgresql

matrix:
  fast_finish: true
  include:
    # - php: 5.5
    - php: 5.6
    # - php: 7.0
    # - php: 7.1

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update # May help using cache for php packages.
  # - ls /home/travis/.phpenv/versions/5.6/etc/conf.d
  # - phpenv config-add ~travis.php.ini # name choosen for it to be executed after travis.ini
  # - ls /home/travis/.phpenv/versions/5.6/etc/conf.d
  #^ Shows the (alphabetical) order used for execution, last executed overrides the parameters
  # - psql -c 'create database travis_ci_test;' -U postgres

install:
  # - composer install --no-scripts --no-progress --no-suggest
  # - cp config/parameters.yml.travis config/parameters.yml
  # - composer up --no-progress --no-suggest --optimize-autoloader --apcu-autoloader
  - composer install --no-progress --no-suggest --optimize-autoloader --apcu-autoloader

before_script:

script:
  # - ./vendor/bin/simple-phpunit
  # this checks that the source code follows the Symfony Code Syntax rules
  - ./vendor/bin/php-cs-fixer fix --diff --dry-run -v
  # this checks that the YAML config files contain no syntax errors
  # - ./bin/console lint:yaml config
  # - ./bin/console lint:yaml @CodeExplorerBundle
  # this checks that the Twig template files contain no syntax errors
  # - ./bin/console lint:twig templates @CodeExplorerBundle
  # this checks that the XLIFF translations contain no syntax errors
  # - ./bin/console lint:xliff templates
  # this checks that the application doesn't use dependencies with known security vulnerabilities
  # - ./bin/console security:check --end-point=http://security.sensiolabs.org/check_lock

# inspirated from symfony/symfony-demo
