---
sudo: false
cache:
  directories:
    - $HOME/.composer/cache/files

language: php
# php: 7.1
# env: # Important!
matrix:
  fast_finish: true
  exclude: # To use less CPU during debug, but remains without effect!
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.2
    - php: nightly
    # - php: 5.4
  include:
    - php: 5.6
      env:
        - PHPUNIT=phpunit-5.7
        - TEST_LINT=`true`
        - PHP_CS_FIXER=`true`
        - SENSIO_SECURITY=`true`
    - php: 7.0
      env:
        - PHPUNIT=phpunit
        - TEST_LINT=`true`
        - PHP_CS_FIXER=`true`
        - SENSIO_SECURITY=`true`
    - php: 7.1
      env:
        - PHPUNIT=phpunit
        - TEST_LINT=`true`
        - PHP_CS_FIXER=`true`
        - SENSIO_SECURITY=`true`
#    - php: 5.4 # symfony/http-kernel v3.3.6 requires php >=5.5.9 -> your PHP version (5.4.45) does not satisfy that requirement.
#    - php: 5.5
#       env:
#         - PHPUNIT=phpunit-4.8
#         - TEST_LINT=`true`
#         - SENSIO_SECURITY=`true`
#    - php: 7.2
#       env:
#         - PHPUNIT=phpunit
#         - TEST_LINT=`true`
#         - SENSIO_SECURITY=`true`
#     - php: nightly
#       env:
#         - PHPUNIT=phpunit
#         - TEST_LINT=`true`
#         - SENSIO_SECURITY=`true`
  allow_failures:
    - php: 5.4
    - php: 5.5 # needs older phpunit
    - php: 7.2
    - php: nightly

before_install:
  - echo $PHPUNIT
  - pwd
  - echo $HOME
  - echo $TRAVIS_PHP_VERSION
  - which composer
  - ls /tmp
  - php --ini
  - xdebug=/home/travis/.phpenv/versions/$TRAVIS_PHP_VERSION/etc/conf.d/xdebug.ini
  - if [[ -f $xdebug ]]; then cat $xdebug; cp $xdebug /tmp; phpenv config-rm xdebug.ini; fi
  - xdebug_php=
  - if [[ -f /tmp/xdebug.ini ]]; then xdebug_php='-c /tmp/xdebug.ini'; fi
  - install --directory .travis/bin
  - if [[ -v PHP_CS_FIXER ]]; then wget http://cs.sensiolabs.org/download/php-cs-fixer-v2.phar --output-document=.travis/bin/php-cs-fixer; fi
  - if [[ -v PHPUNIT ]]; then wget https://phar.phpunit.de/${PHPUNIT}.phar --output-document=.travis/bin/$PHPUNIT; fi
  - if [[ -v SENSIO_SECURITY ]]; then wget http://get.sensiolabs.org/security-checker.phar --output-document=.travis/bin/security-checker; fi

install:
  - composer validate
  - composer install --no-scripts --no-progress --no-suggest
  - if [[ -f config/parameters.yml.travis ]]; then cp config/parameters.yml.travis config/parameters.yml; fi
  - composer up --no-progress --no-suggest --optimize-autoloader --apcu-autoloader
  - composer show
  - env KERNEL_DIR=tests/FrameworkTwig/src php tests/FrameworkTwig/bin/console

before_script:

script:
  - for f in $(find . -path './vendor' -prune -o -path './tests' -prune -o -name \*.php -print) ; do php -l $f ; done # Do this first!
  - if [[ -v TEST_LINT ]]; then for f in $(find ./tests -name \*.php -print); do php -l $f; done; fi
  - if [[ -v PHP_CS_FIXER ]]; then php .travis/bin/php-cs-fixer --version; fi
  - if [[ -v PHP_CS_FIXER ]]; then php .travis/bin/php-cs-fixer fix --stop-on-violation --diff --dry-run -vvv --using-cache=no; fi
  - if [[ -v PHPUNIT ]]; then php --ini $xdebug_php; fi
  - if [[ -v PHPUNIT ]]; then php $xdebug_php .travis/bin/$PHPUNIT --configuration tests/FrameworkTwig/phpunit.xml --repeat 1; fi
  - if [[ -v PHPUNIT ]]; then php $xdebug_php .travis/bin/$PHPUNIT --configuration tests/Framework/phpunit.xml --repeat 1; fi
  - if [[ -v PHPUNIT ]]; then php $xdebug_php .travis/bin/$PHPUNIT --configuration tests/Component/phpunit.xml --debug; fi

  - if [[ -v SENSIO_SECURITY ]]; then php .travis/bin/security-checker security:check --end-point=http://security.sensiolabs.org/check_lock; fi
    #^ This checks that the application doesn't use dependencies with known security vulnerabilities
  - if [[ -v VENDOR_LINT ]]; then for f in $(find ./vendor -name \*.php); do php -l $f > /dev/null; done; fi
    #^ Should be the last line of install but sometimes long to execute and little can be done for errors found.
  - env KERNEL_DIR=tests/FrameworkTwig/src php tests/FrameworkTwig/bin/console server:start -vvv
  - w3m http://127.0.0.1:8000/constructor | cat
  - w3m http://127.0.0.1:8000/argument | cat
  - w3m http://127.0.0.1:8000/variadic/request | cat

after_success:
    - true || bash <(curl -s https://codecov.io/bash) -s /tmp

# inspirated from:
  # symfony/symfony-demo
  # https://github.com/doctrine/dbal/blob/v2.5.13/.travis.yml
